iOS: Mark FerrostarCoreFFI as @preconcurrency (#632)
* iOS: Mark FerrostarCoreFFI as @preconcurrency

This will then allow DemoAppState to be interpreted as Sendable, thus removing the warning from DemoError.

```
/Users/bolsinga/Documents/code/git/ferrostar/apple/DemoApp/Demo/DemoError.swift:9:10: error: associated value 'invalidState' of 'Sendable'-conforming enum 'DemoError' has non-sendable type 'DemoAppState'
    case invalidState(DemoAppState)
         ^
/Users/bolsinga/Documents/code/git/ferrostar/apple/DemoApp/Demo/DemoAppState.swift:5:6: note: consider making enum 'DemoAppState' conform to the 'Sendable' protocol
enum DemoAppState: CustomStringConvertible {
     ^
                                          , Sendable
```

* Update apple/DemoApp/Demo/DemoAppState.swift

* swiftformat

---------

Co-authored-by: Ian Wagner <ianwagner+github@switzerlandmail.ch>
Co-authored-by: Ian Wagner <ian.wagner@stadiamaps.com>